### ISSUE TITLE
iOS Linking

### ISSUE THREAD

**Issue by bell-steven** [ConduitMobileRND/react-native-simple-shadow-view#4]
Great Library here. I could not find anything else to do this well.

I am curious about some of the documentation and implementation of iOS Linking.

When I run `react-native link react-native-simple-shadow-view` Android is linking, but not iOS. 
This makes sense to me. When using iOS everything seems to be passing through just fine without linking, which is great. 
But, I noticed in the docs you have iOS manual linking instructions. Is there something that I am missing here? Is Linking iOS necessary?

Thanks again for this awesome Library!

**Comment by rborn** [comment]
I think is just an oversight from a "template" readme.
